spring.application.name: core-api

spring:
  config:
    import:
      - monitoring.yml
      - logging.yml
  web.resources.add-mappings: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 100

server:
  forward-headers-strategy: framework
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: .*
    use-relative-redirects: true
  servlet:
    session:
      cookie:
        secure: true

jwt:
  expiration_time: 86400000
  secret: ${JWT_SECRET_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
    directory: ${AWS_S3_DIRECTORY}
  region: ${AWS_REGION}
  stack:
    auto: false

---
spring.config.activate.on-profile: local

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/login/oauth2/code/google
naver:
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/login/oauth2/code/naver
kakao:
  client:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/login/oauth2/code/kakao

cloud:
  s3:
    directory: test

---
spring.config.activate.on-profile: dev

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: https://easyroutine.heykiwoung.com/login/oauth2/code/google
naver:
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: https://easyroutine.heykiwoung.com/login/oauth2/code/naver
kakao:
  client:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: https://easyroutine.heykiwoung.com/login/oauth2/code/kakao

cloud:
  s3:
    directory: test

---
spring.config.activate.on-profile: live

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: https://www.healper.shop/login/oauth2/code/google
naver:
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: https://www.healper.shop/login/oauth2/code/naver
kakao:
  client:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: https://www.healper.shop/login/oauth2/code/kakao

cloud:
  s3:
    directory: prod

---
spring.config.activate.on-profile: test

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/login/oauth2/code/google
naver:
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/login/oauth2/code/naver
kakao:
  client:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/login/oauth2/code/kakao
